# Generated by Django 5.0.1 on 2024-01-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='constituency',
            field=models.CharField(choices=[('Shangri-la-Town', 'Shangri-la-Town'), ('Northern-Kunlun-Mountain', 'Northern-Kunlun-Mountain'), ('Western-Shangri-la', 'Western-Shangri-la'), ('Naboo-Vallery', 'Naboo-Vallery'), ('New-Felucia', 'New-Felucia')], default='Shangri-la-Town', max_length=50),
        ),
    ]
