# Generated by Django 5.0.1 on 2024-01-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0002_voter_constituency"),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="uvc",
            field=models.CharField(default="HH64FWPE", max_length=20, unique=True),
        ),
    ]
