# Generated by Django 5.0.1 on 2024-01-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_alter_voter_uvc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='uvc',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
