# Generated by Django 5.0.1 on 2024-01-13 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_alter_voter_uvc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='uvc',
        ),
    ]
