# Generated by Django 5.0.1 on 2024-01-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0012_remove_voter_uvc'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='uvc',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
