# Generated by Django 5.0.1 on 2024-01-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0014_alter_candidate_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, default='images/profile1.jpg', null=True, upload_to='candidates'),
        ),
    ]
