# Generated by Django 5.0.1 on 2024-01-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0015_alter_candidate_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(default='profile1.jpg', upload_to='candidates'),
        ),
    ]
