# Generated by Django 5.0.1 on 2024-01-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0016_alter_candidate_bio_alter_candidate_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(default='candidates/profile1.jpg', upload_to='candidates'),
        ),
    ]
